Class {
	#name : 'CESimTargetingProfile',
	#superclass : 'Object',
	#category : 'BV-Catalyst-Ecosystems-Sim-Core',
	#package : 'BV-Catalyst-Ecosystems-Sim-Core'
}

{ #category : 'targeting profile' }
CESimTargetingProfile class >> inspect [
	^ #inspectTargetingProfile
]

{ #category : 'targeting profile' }
CESimTargetingProfile class >> interact [
	^ #interactTargetingProfile
]

{ #category : 'targeting profile' }
CESimTargetingProfile class >> targetedStimulus [
	^ #targetedStimulusTargetingProfile
]

{ #category : 'profiles' }
CESimTargetingProfile class >> focus [
	^ #focusTargetingProfile
]
