Class {
	#name : 'CESimBehaviourModule',
	#superclass : 'Object',
	#category : 'BV-Catalyst-Ecosystems-Sim-Core',
	#package : 'BV-Catalyst-Ecosystems-Sim-Core'
}

{ #category : 'producing' }
CESimBehaviourModule >> produceEventsIntoUpdate: aCESimUpdate inContext: aCESimRunContext [
	"Default: no events."
]

{ #category : 'producing' }
CESimBehaviourModule >> produceOperationsIntoUpdate: aCESimUpdate inContext: aCESimRunContext [
	"Default: no operations."
]
